RGSRC=../../../../..
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../../../envir.mak

SO_TARGET=libmanagement.so
O_OBJS=Classpath.o JIT.o Debug.o XProfiler.o

RAMDISK_LIB_FILES+=libmanagement.so

include $(RGMK)
