# File: drivers/at91/serial/Makefile
#
# Makefile for the Atmel AT91RM9200 serial and console device drivers
#

O_TARGET := at91serial.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_SERIAL_AT91) += at91_serial.o

include $(TOPDIR)/Rules.make
