RGSRC=../../../../
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../crypto_env.mak

EXPORT_HEADERS=ecdh.h
INTERNAL_HEADERS=ech_locl.h

O_OBJS=ech_lib.o ech_ossl.o ech_key.o ech_err.o

include $(RGMK)

