RGSRC=../../..
include $(RGSRC)/envir.mak

INTERNAL_HEADERS=algorithm basic_definitions bitset cassert cctype cerrno \
  cfloat char_traits climits clocale cmath complex csetjmp csignal cstdarg \
  cstddef cstdio cstdlib cstring ctime cwchar cwctype deque exception fstream \
  func_exception functional iomanip ios iosfwd iostream istream \
  istream_helpers iterator iterator_base list locale map memory new numeric \
  ostream ostream_helpers queue set sstream stack stdexcept streambuf string \
  string_iostream support type_traits typeinfo utility valarray vector \
  system_configuration.h

include $(RGMK)
