RGSRC=../../../../
include $(RGSRC)/envir.mak

EXPORT_HEADERS_DIR+=types
SUBDIRS+=
EXPORT_HEADERS+=acl.h      capture.h   freq_ctr.h  lb_chash.h  log.h         protocols.h   queue.h    stick_table.h auth.h     checks.h    global.h    lb_fwlc.h   pattern.h     proto_http.h  server.h   stream_interface.h backend.h  counters.h  hdr_idx.h   lb_fwrr.h   pipe.h        proto_tcp.h   session.h  task.h buffers.h  fd.h        httperr.h   lb_map.h    port_range.h  proxy.h       signal.h   template.h

include $(RGMK)





