/****************************************************************************
 *
 * rg/pkg/util/kos_26_mod.c
 * 
 * Copyright (C) Jungo LTD 2004
 * 
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General 
 * Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at
 * your option) any later version.
 * 
 * This program is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
 * MA 02111-1307, USA.
 *
 * Developed by Jungo LTD.
 * Residential Gateway Software Division
 * www.jungo.com
 * info@jungo.com
 */

/* This file is originaly autogenerated by linux-2.6 kbuild system.
 * We use this pre-made version of this file to enable building modules before
 * the kernel is built.
 *
 * By using this pre-made file we disable modprobe's ability to auto-detect the
 * modules dependencies
 */

#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

#ifndef CONFIG_RG_UML
/* 
 * In UML, some modules, e.g. kos, are exported as binaries and thus compiled 
 * in Jungo, while the linux kernel is exported as src and compiles using the 
 * customer's host machine gcc.
 * This cause the following vermagic check to fail during insmod if the gcc
 * versions are not the same.
 */
MODULE_INFO(vermagic, VERMAGIC_STRING);
#endif

#undef unix
struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
 .name = __stringify(KBUILD_MODNAME),
 .init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
 .exit = cleanup_module,
#endif
};

static const char __module_depends[]
__attribute_used__
__attribute__((section(".modinfo"))) =
"depends=";
