RGSRC=../../../../
include $(RGSRC)/envir.mak

EXPORT_HEADERS_DIR+=proto
SUBDIRS+=
EXPORT_HEADERS+=acl.h      checks.h     fd.h        lb_chash.h  log.h      port_range.h  proto_uxst.h  session.h           stream_sock.h auth.h     client.h     freq_ctr.h  lb_fwlc.h   Makefile   protocols.h   proxy.h       signal.h            task.h backend.h  cttproxy.h   hdr_idx.h   lb_fwrr.h   pattern.h  proto_http.h  queue.h       stick_table.h       template.h buffers.h  dumpstats.h  httperr.h   lb_map.h    pipe.h     proto_tcp.h   server.h      stream_interface.h

include $(RGMK)





