# File: drivers/at91/usb/Makefile
#
# Makefile for the Atmel AT91RM9200 USB device drivers
#

O_TARGET := at91usb.o

export-objs :=

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_USB_OHCI_AT91) += at91_usb-ohci.o

include $(TOPDIR)/Rules.make
