RGSRC=../../../../..
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../../../envir.mak

SO_TARGET=libio.so
O_OBJS=File.o \
	java_io_VMObjectInputStream.o \
	java_io_VMObjectStreamClass.o

RAMDISK_LIB_FILES+=libio.so

include $(RGMK)
