# Simple makefile to illustrate  md5 operation.
#
#  Copyright 2005 Indranet Technologies Ltd
#
# $Log: Makefile,v $
# Revision 1.2  2005/08/14 09:57:16  dmitry
# B25117. Merged pwlib version 1_9_0 from vendor branch.
#
# Revision 1.1.2.1  2005/08/14 09:51:45  dmitry
# Added pwlib version 1.9.0 from pwlib-v1_9_0-src-tar.gz
#
# Revision 1.1  2005/03/02 21:50:02  dereksmithies
# Initial release of example code to calculate MD5 sums of a supplied string.
#
#
#
PROG    = md5
SOURCES = encrypt.cxx


ifndef PWLIBDIR
PWLIBDIR=$(HOME)/pwlib
endif

include $(PWLIBDIR)/make/ptlib.mak

# End of Makefile
