# File: drivers/at91/watchdog/Makefile
#
# Makefile for the Atmel AT91RM9200 watchdog device driver
#

O_TARGET := at91wdt.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_AT91_WATCHDOG) += at91_wdt.o

include $(TOPDIR)/Rules.make
