RGSRC=../../../../..
include $(RGSRC)/envir.mak
include $(RGSRC)/pkg/voip/asterisk/db1-ast/common.mak

O_TARGET=recno_target.o
O_OBJS=rec_close.o rec_delete.o rec_get.o rec_open.o rec_put.o rec_search.o \
  rec_seq.o rec_utils.o

include $(RGMK)
