include .config
include scripts/Makefile.lib

RGSRC=$(srctree)/../..
include $(RGSRC)/envir.mak

# find all modules listed in $(MODVERDIR)/
__modules := $(sort $(shell grep -h '\.ko' /dev/null $(wildcard $(MODVERDIR)/*.mod)))
modules   := $(patsubst %.o,%.ko, $(wildcard $(__modules:.ko=.o)))

RAMDISK_KERNEL_MODULES+=$(modules)

# copy them to ramdisk by making our "ramdisk" target
.PHONY: all
all: ramdisk 

include $(RGSRC)/copy_db_envir.mak
include $(RGSRC)/copy_db.mak

