RGSRC=../../../../
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../crypto_env.mak

EXPORT_HEADERS=sha.h sha1dgst.c__c/sha1dgst.c
INTERNAL_HEADERS=sha_locl.h

O_OBJS=sha_dgst.o sha1dgst.o sha_one.o sha1_one.o sha256.o sha512.o

include $(RGMK)

