RGSRC=../../../../
include $(RGSRC)/envir.mak

EXPORT_HEADERS_DIR+=common
SUBDIRS+=
EXPORT_HEADERS+=pre_init.h appsession.h  cfgparse.h  compiler.h  debug.h     epoll.h   memory.h      rbtree.h  sessionhash.h  template.h  time.h   uri_auth.h base64.h      compat.h    config.h    defaults.h  errors.h  mini-clist.h  regex.h   standard.h     ticks.h     tools.h  version.h

include $(RGMK)





