RGSRC=../../../../..
include $(RGSRC)/envir.mak

O_TARGET=target.o
O_OBJS=add.o code.o decode.o long_term.o lpc.o preprocess.o rpe.o \
  gsm_destroy.o gsm_decode.o gsm_encode.o gsm_create.o gsm_option.o \
  short_term.o table.o

include $(RGMK)
