/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_gnu_java_nio_VMSelector
#define _Included_gnu_java_nio_VMSelector

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class gnu_java_nio_VMSelector */

typedef struct Hgnu_java_nio_VMSelector {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from gnu/java/nio/VMSelector: */
} Hgnu_java_nio_VMSelector;

extern jint gnu_java_nio_VMSelector_select(HArrayOfInt*, HArrayOfInt*, HArrayOfInt*, jlong);

#ifdef __cplusplus
}
#endif

#endif
