/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_nio_charset_iconv_IconvEncoder
#define _Included_gnu_java_nio_charset_iconv_IconvEncoder

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_nio_charset_iconv_IconvEncoder_STATE_RESET
#define gnu_java_nio_charset_iconv_IconvEncoder_STATE_RESET 0L
#undef gnu_java_nio_charset_iconv_IconvEncoder_STATE_CODING
#define gnu_java_nio_charset_iconv_IconvEncoder_STATE_CODING 1L
#undef gnu_java_nio_charset_iconv_IconvEncoder_STATE_END
#define gnu_java_nio_charset_iconv_IconvEncoder_STATE_END 2L
#undef gnu_java_nio_charset_iconv_IconvEncoder_STATE_FLUSHED
#define gnu_java_nio_charset_iconv_IconvEncoder_STATE_FLUSHED 3L
JNIEXPORT void JNICALL Java_gnu_java_nio_charset_iconv_IconvEncoder_openIconv(JNIEnv*, jobject, jstring);
JNIEXPORT jint JNICALL Java_gnu_java_nio_charset_iconv_IconvEncoder_encode(JNIEnv*, jobject, jcharArray, jbyteArray, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_nio_charset_iconv_IconvEncoder_closeIconv(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
