/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_classpath_VMSystemProperties
#define _Included_gnu_classpath_VMSystemProperties

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_gnu_classpath_VMSystemProperties_postInit(JNIEnv*, jclass, jobject);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getLocale(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getKaffeLibraryPath(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getSunBootClassPath(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getJavaClassPath(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getJavaHome(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getJavaIoTmpdir(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getJavaCompiler(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getOsName(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getOsArch(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getOsVersion(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getFileSeparator(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getPathSeparator(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getLineSeparator(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getUserName(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getUserHome(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getUserDir(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_gnu_classpath_VMSystemProperties_getGnuCpuEndian(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif

#endif
