/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_gnu_java_net_SysInetAddressImpl
#define _Included_gnu_java_net_SysInetAddressImpl

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class gnu_java_net_SysInetAddressImpl */

typedef struct Hgnu_java_net_SysInetAddressImpl {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from gnu/java/net/SysInetAddressImpl: */
} Hgnu_java_net_SysInetAddressImpl;

extern struct Hjava_lang_String* gnu_java_net_SysInetAddressImpl_getHostByAddr(struct Hgnu_java_net_SysInetAddressImpl*, HArrayOfByte*);
extern HArrayOfArray* gnu_java_net_SysInetAddressImpl_getHostByName(struct Hgnu_java_net_SysInetAddressImpl*, struct Hjava_lang_String*);

#ifdef __cplusplus
}
#endif

#endif
