/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_gnu_java_nio_channels_FileChannelImpl
#define _Included_gnu_java_nio_channels_FileChannelImpl

#ifdef __cplusplus
extern "C" {
#endif

#undef gnu_java_nio_channels_FileChannelImpl_READ
#define gnu_java_nio_channels_FileChannelImpl_READ 1L
#undef gnu_java_nio_channels_FileChannelImpl_WRITE
#define gnu_java_nio_channels_FileChannelImpl_WRITE 2L
#undef gnu_java_nio_channels_FileChannelImpl_APPEND
#define gnu_java_nio_channels_FileChannelImpl_APPEND 4L
#undef gnu_java_nio_channels_FileChannelImpl_EXCL
#define gnu_java_nio_channels_FileChannelImpl_EXCL 8L
#undef gnu_java_nio_channels_FileChannelImpl_SYNC
#define gnu_java_nio_channels_FileChannelImpl_SYNC 16L
#undef gnu_java_nio_channels_FileChannelImpl_DSYNC
#define gnu_java_nio_channels_FileChannelImpl_DSYNC 32L
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_init(JNIEnv*, jclass);
JNIEXPORT jint JNICALL Java_gnu_java_nio_channels_FileChannelImpl_open(JNIEnv*, jobject, jstring, jint);
JNIEXPORT jint JNICALL Java_gnu_java_nio_channels_FileChannelImpl_available(JNIEnv*, jobject);
JNIEXPORT jlong JNICALL Java_gnu_java_nio_channels_FileChannelImpl_implPosition(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_seek(JNIEnv*, jobject, jlong);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_implTruncate(JNIEnv*, jobject, jlong);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_unlock(JNIEnv*, jobject, jlong, jlong);
JNIEXPORT jlong JNICALL Java_gnu_java_nio_channels_FileChannelImpl_size(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_implCloseChannel(JNIEnv*, jobject);
JNIEXPORT jint JNICALL Java_gnu_java_nio_channels_FileChannelImpl_read__(JNIEnv*, jobject);
JNIEXPORT jint JNICALL Java_gnu_java_nio_channels_FileChannelImpl_read___3BII(JNIEnv*, jobject, jbyteArray, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_write___3BII(JNIEnv*, jobject, jbyteArray, jint, jint);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_write__I(JNIEnv*, jobject, jint);
JNIEXPORT jobject JNICALL Java_gnu_java_nio_channels_FileChannelImpl_mapImpl(JNIEnv*, jobject, jchar, jlong, jint);
JNIEXPORT void JNICALL Java_gnu_java_nio_channels_FileChannelImpl_force(JNIEnv*, jobject);
JNIEXPORT jboolean JNICALL Java_gnu_java_nio_channels_FileChannelImpl_lock(JNIEnv*, jobject, jlong, jlong, jboolean, jboolean);

#ifdef __cplusplus
}
#endif

#endif
