/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_gnu_classpath_VMStackWalker
#define _Included_gnu_classpath_VMStackWalker

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class gnu_classpath_VMStackWalker */

typedef struct Hgnu_classpath_VMStackWalker {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from gnu/classpath/VMStackWalker: */
#undef gnu_classpath_VMStackWalker_MINIMAL_NUMBER_OF_FRAMES
#define gnu_classpath_VMStackWalker_MINIMAL_NUMBER_OF_FRAMES 4L
#undef gnu_classpath_VMStackWalker_CALLERS_CALLER_FRAME
#define gnu_classpath_VMStackWalker_CALLERS_CALLER_FRAME 3L
} Hgnu_classpath_VMStackWalker;

extern HArrayOfObject* gnu_classpath_VMStackWalker_getClassContext(void);
extern struct Hjava_lang_Class* gnu_classpath_VMStackWalker_getCallingClass(void);
extern struct Hjava_lang_ClassLoader* gnu_classpath_VMStackWalker_getCallingClassLoader(void);

#ifdef __cplusplus
}
#endif

#endif
