/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_nio_MappedByteBufferImpl
#define _Included_java_nio_MappedByteBufferImpl

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_unmapImpl(JNIEnv*, jobject);
JNIEXPORT jboolean JNICALL Java_java_nio_MappedByteBufferImpl_isLoadedImpl(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_loadImpl(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_java_nio_MappedByteBufferImpl_forceImpl(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif

#endif
