/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_zip_ZipEntry
#define _Included_java_util_zip_ZipEntry

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_zip_ZipEntry */

typedef struct Hjava_util_zip_ZipEntry {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/zip/ZipEntry: */
#undef java_util_zip_ZipEntry_STORED
#define java_util_zip_ZipEntry_STORED 0L
#undef java_util_zip_ZipEntry_DEFLATED
#define java_util_zip_ZipEntry_DEFLATED 8L
  struct Hjava_lang_String* name;
  jlong time;
  jint dosTime;
  jlong crc;
  jlong size;
  jint method;
  HArrayOfByte* extra;
  struct Hjava_lang_String* comment;
  jint flag;
  jint version;
  jlong csize;
  jlong offset;
} Hjava_util_zip_ZipEntry;


#ifdef __cplusplus
}
#endif

#endif
