/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_security_VMAccessController
#define _Included_java_security_VMAccessController

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_security_VMAccessController */

typedef struct Hjava_security_VMAccessController {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/security/VMAccessController: */
#undef java_security_VMAccessController_DEBUG
#define java_security_VMAccessController_DEBUG 0L
} Hjava_security_VMAccessController;

extern HArrayOfArray* java_security_VMAccessController_getStack(void);

#ifdef __cplusplus
}
#endif

#endif
