/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_lang_ref_Reference
#define _Included_java_lang_ref_Reference

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_java_lang_ref_Reference_create(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif
