/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Throwable
#define _Included_java_lang_Throwable

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Throwable */

typedef struct Hjava_lang_Throwable {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Throwable: */
#undef java_lang_Throwable_serialVersionUID
#define java_lang_Throwable_serialVersionUID -3042686055658047285LL
  struct Hjava_lang_String* detailMessage;
  struct Hjava_lang_Throwable* cause;
  HArrayOfObject* stackTrace;
  struct Hjava_lang_VMThrowable* vmState;
} Hjava_lang_Throwable;


#ifdef __cplusplus
}
#endif

#endif
