/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_PrintStream
#define _Included_java_io_PrintStream

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_PrintStream */

typedef struct Hjava_io_PrintStream {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/OutputStream: */

  /* Fields from java/io/FilterOutputStream: */
  struct Hjava_io_OutputStream* out;

  /* Fields from java/io/PrintStream: */
  struct Hjava_lang_String* encoding;
  jboolean error_occurred;
  jboolean auto_flush;
} Hjava_io_PrintStream;


#ifdef __cplusplus
}
#endif

#endif
