/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_RandomAccessFile
#define _Included_java_io_RandomAccessFile

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_RandomAccessFile */

typedef struct Hjava_io_RandomAccessFile {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/RandomAccessFile: */
  struct Hgnu_java_nio_channels_FileChannelImpl* ch;
  struct Hjava_io_FileDescriptor* fd;
  struct Hjava_io_DataOutputStream* out;
  struct Hjava_io_DataInputStream* in;
} Hjava_io_RandomAccessFile;


#ifdef __cplusplus
}
#endif

#endif
