/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Cloneable
#define _Included_java_lang_Cloneable

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Cloneable */

typedef struct Hjava_lang_Cloneable {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Cloneable: */
} Hjava_lang_Cloneable;


#ifdef __cplusplus
}
#endif

#endif
