/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_NetworkInterface
#define _Included_java_net_NetworkInterface

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_NetworkInterface */

typedef struct Hjava_net_NetworkInterface {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/NetworkInterface: */
  struct Hjava_lang_String* name;
  struct Hjava_util_Vector* inetAddresses;
} Hjava_net_NetworkInterface;


#ifdef __cplusplus
}
#endif

#endif
