/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_reflect_Array
#define _Included_java_lang_reflect_Array

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_reflect_Array */

typedef struct Hjava_lang_reflect_Array {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/reflect/Array: */
#undef java_lang_reflect_Array_SEPARATOR
#define java_lang_reflect_Array_SEPARATOR "."
} Hjava_lang_reflect_Array;

extern jint java_lang_reflect_Array_getLength(struct Hjava_lang_Object*);
extern struct Hjava_lang_Object* java_lang_reflect_Array_newArray(struct Hjava_lang_Class*, jint);

#ifdef __cplusplus
}
#endif

#endif
