/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Object
#define _Included_java_lang_Object

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Object */


#ifdef __cplusplus
}
#endif

#endif
