/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_zip_CRC32
#define _Included_java_util_zip_CRC32

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_zip_CRC32 */

typedef struct Hjava_util_zip_CRC32 {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/zip/CRC32: */
  jint crc;
} Hjava_util_zip_CRC32;

extern void java_util_zip_CRC32_update(struct Hjava_util_zip_CRC32*, HArrayOfByte*, jint, jint);
extern void java_util_zip_CRC32_update1(struct Hjava_util_zip_CRC32*, jint);

#ifdef __cplusplus
}
#endif

#endif
