/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_InputStream
#define _Included_java_io_InputStream

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_InputStream */

typedef struct Hjava_io_InputStream {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/InputStream: */
} Hjava_io_InputStream;


#ifdef __cplusplus
}
#endif

#endif
