/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_VMClass
#define _Included_java_lang_VMClass

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_VMClass */

typedef struct Hjava_lang_VMClass {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/VMClass: */
} Hjava_lang_VMClass;

extern jboolean java_lang_VMClass_isInstance(struct Hjava_lang_Class*, struct Hjava_lang_Object*);
extern jboolean java_lang_VMClass_isAssignableFrom(struct Hjava_lang_Class*, struct Hjava_lang_Class*);
extern jboolean java_lang_VMClass_isInterface(struct Hjava_lang_Class*);
extern jboolean java_lang_VMClass_isPrimitive(struct Hjava_lang_Class*);
extern struct Hjava_lang_String* java_lang_VMClass_getName(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_VMClass_getSuperclass(struct Hjava_lang_Class*);
extern HArrayOfObject* java_lang_VMClass_getInterfaces(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_VMClass_getComponentType(struct Hjava_lang_Class*);
extern jint java_lang_VMClass_getModifiers(struct Hjava_lang_Class*, jboolean);
extern struct Hjava_lang_Class* java_lang_VMClass_getDeclaringClass(struct Hjava_lang_Class*);
extern HArrayOfObject* java_lang_VMClass_getDeclaredClasses(struct Hjava_lang_Class*, jboolean);
extern HArrayOfObject* java_lang_VMClass_getDeclaredFields(struct Hjava_lang_Class*, jboolean);
extern HArrayOfObject* java_lang_VMClass_getDeclaredMethods(struct Hjava_lang_Class*, jboolean);
extern HArrayOfObject* java_lang_VMClass_getDeclaredConstructors(struct Hjava_lang_Class*, jboolean);
extern struct Hjava_lang_ClassLoader* java_lang_VMClass_getClassLoader(struct Hjava_lang_Class*);
extern jboolean java_lang_VMClass_isArray(struct Hjava_lang_Class*);
extern void java_lang_VMClass_initialize(struct Hjava_lang_Class*);
extern struct Hjava_lang_Class* java_lang_VMClass_loadArrayClass(struct Hjava_lang_String*, struct Hjava_lang_ClassLoader*);
extern void java_lang_VMClass_throwException(struct Hjava_lang_Throwable*);
extern void java_lang_VMClass_checkAccess(struct Hjava_lang_Class*, struct Hjava_lang_Class*, jint);

#ifdef __cplusplus
}
#endif

#endif
