/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_FileInputStream
#define _Included_java_io_FileInputStream

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_FileInputStream */

typedef struct Hjava_io_FileInputStream {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/InputStream: */

  /* Fields from java/io/FileInputStream: */
  struct Hjava_io_FileDescriptor* fd;
  struct Hgnu_java_nio_channels_FileChannelImpl* ch;
} Hjava_io_FileInputStream;


#ifdef __cplusplus
}
#endif

#endif
