/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_Comparator
#define _Included_java_util_Comparator

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_Comparator */

typedef struct Hjava_util_Comparator {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/Comparator: */
} Hjava_util_Comparator;


#ifdef __cplusplus
}
#endif

#endif
