/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_math_BigInteger
#define _Included_java_math_BigInteger

#ifdef __cplusplus
extern "C" {
#endif

#undef java_math_BigInteger_serialVersionUID
#define java_math_BigInteger_serialVersionUID -8742448824652078965LL
#undef java_math_BigInteger_serialVersionUID
#define java_math_BigInteger_serialVersionUID -8287574255936472291LL
#undef java_math_BigInteger_minFixNum
#define java_math_BigInteger_minFixNum -100L
#undef java_math_BigInteger_maxFixNum
#define java_math_BigInteger_maxFixNum 1024L
#undef java_math_BigInteger_numFixNum
#define java_math_BigInteger_numFixNum 1125L
#undef java_math_BigInteger_FLOOR
#define java_math_BigInteger_FLOOR 1L
#undef java_math_BigInteger_CEILING
#define java_math_BigInteger_CEILING 2L
#undef java_math_BigInteger_TRUNCATE
#define java_math_BigInteger_TRUNCATE 3L
#undef java_math_BigInteger_ROUND
#define java_math_BigInteger_ROUND 4L

#ifdef __cplusplus
}
#endif

#endif
