/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_InterruptedIOException
#define _Included_java_io_InterruptedIOException

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_InterruptedIOException */

typedef struct Hjava_io_InterruptedIOException {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Throwable: */
#undef java_io_InterruptedIOException_serialVersionUID
#define java_io_InterruptedIOException_serialVersionUID -3042686055658047285LL
  struct Hjava_lang_String* detailMessage;
  struct Hjava_lang_Throwable* cause;
  HArrayOfObject* stackTrace;
  struct Hjava_lang_VMThrowable* vmState;

  /* Fields from java/lang/Exception: */
#undef java_io_InterruptedIOException_serialVersionUID
#define java_io_InterruptedIOException_serialVersionUID -3387516993124229948LL

  /* Fields from java/io/IOException: */
#undef java_io_InterruptedIOException_serialVersionUID
#define java_io_InterruptedIOException_serialVersionUID 7818375828146090155LL

  /* Fields from java/io/InterruptedIOException: */
#undef java_io_InterruptedIOException_serialVersionUID
#define java_io_InterruptedIOException_serialVersionUID 4020568460727500567LL
  jint bytesTransferred;
} Hjava_io_InterruptedIOException;


#ifdef __cplusplus
}
#endif

#endif
