/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_lang_VMDouble
#define _Included_java_lang_VMDouble

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_java_lang_VMDouble_doubleToLongBits(JNIEnv*, jclass, jdouble);
JNIEXPORT jlong JNICALL Java_java_lang_VMDouble_doubleToRawLongBits(JNIEnv*, jclass, jdouble);
JNIEXPORT jdouble JNICALL Java_java_lang_VMDouble_longBitsToDouble(JNIEnv*, jclass, jlong);
JNIEXPORT jstring JNICALL Java_java_lang_VMDouble_toString(JNIEnv*, jclass, jdouble, jboolean);
JNIEXPORT void JNICALL Java_java_lang_VMDouble_initIDs(JNIEnv*, jclass);
JNIEXPORT jdouble JNICALL Java_java_lang_VMDouble_parseDouble(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif
