/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_reflect_Constructor
#define _Included_java_lang_reflect_Constructor

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_reflect_Constructor */

typedef struct Hjava_lang_reflect_Constructor {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/reflect/AccessibleObject: */
  jboolean flag;

  /* Fields from java/lang/reflect/Constructor: */
  struct Hjava_lang_Class* clazz;
  jint slot;
  HArrayOfObject* parameterTypes;
  HArrayOfObject* exceptionTypes;
} Hjava_lang_reflect_Constructor;

extern jint java_lang_reflect_Constructor_getModifiers(struct Hjava_lang_reflect_Constructor*);

#ifdef __cplusplus
}
#endif

#endif
