/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_VMThrowable
#define _Included_java_lang_VMThrowable

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_VMThrowable */

typedef struct Hjava_lang_VMThrowable {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/VMThrowable: */
  struct Hjava_lang_Object* vmdata;
} Hjava_lang_VMThrowable;

extern void java_lang_VMThrowable_fillInStackTrace(struct Hjava_lang_VMThrowable*);
extern HArrayOfObject* java_lang_VMThrowable_getStackTrace(struct Hjava_lang_VMThrowable*, struct Hjava_lang_Throwable*);

#ifdef __cplusplus
}
#endif

#endif
