/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_VMObject
#define _Included_java_lang_VMObject

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_VMObject */

typedef struct Hjava_lang_VMObject {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/VMObject: */
} Hjava_lang_VMObject;

extern struct Hjava_lang_Class* java_lang_VMObject_getClass(struct Hjava_lang_Object*);
extern struct Hjava_lang_Object* java_lang_VMObject_clone(struct Hjava_lang_Cloneable*);
extern void java_lang_VMObject_notify(struct Hjava_lang_Object*);
extern void java_lang_VMObject_notifyAll(struct Hjava_lang_Object*);
extern void java_lang_VMObject_wait(struct Hjava_lang_Object*, jlong, jint);

#ifdef __cplusplus
}
#endif

#endif
