/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_File
#define _Included_java_io_File

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_File */

typedef struct Hjava_io_File {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/File: */
#undef java_io_File_serialVersionUID
#define java_io_File_serialVersionUID 301077366599181567LL
  struct Hjava_lang_String* path;
} Hjava_io_File;


#ifdef __cplusplus
}
#endif

#endif
