/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_SocketAddress
#define _Included_java_net_SocketAddress

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_SocketAddress */

typedef struct Hjava_net_SocketAddress {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/SocketAddress: */
#undef java_net_SocketAddress_serialVersionUID
#define java_net_SocketAddress_serialVersionUID 5215720748342549866LL
} Hjava_net_SocketAddress;


#ifdef __cplusplus
}
#endif

#endif
