/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_FileOutputStream
#define _Included_java_io_FileOutputStream

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_FileOutputStream */

typedef struct Hjava_io_FileOutputStream {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/OutputStream: */

  /* Fields from java/io/FileOutputStream: */
  struct Hjava_io_FileDescriptor* fd;
  struct Hgnu_java_nio_channels_FileChannelImpl* ch;
} Hjava_io_FileOutputStream;


#ifdef __cplusplus
}
#endif

#endif
