/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_io_VMObjectInputStream
#define _Included_java_io_VMObjectInputStream

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_java_io_VMObjectInputStream_allocateObject(JNIEnv*, jclass, jclass, jclass, jobject);

#ifdef __cplusplus
}
#endif

#endif
