/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_lang_VMFloat
#define _Included_java_lang_VMFloat

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_java_lang_VMFloat_floatToIntBits(JNIEnv*, jclass, jfloat);
JNIEXPORT jint JNICALL Java_java_lang_VMFloat_floatToRawIntBits(JNIEnv*, jclass, jfloat);
JNIEXPORT jfloat JNICALL Java_java_lang_VMFloat_intBitsToFloat(JNIEnv*, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif
