/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Long
#define _Included_java_lang_Long

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Long */

typedef struct Hjava_lang_Long {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Number: */
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID -8742448824652078965LL

  /* Fields from java/lang/Long: */
#undef java_lang_Long_serialVersionUID
#define java_lang_Long_serialVersionUID 4290774380558885855LL
#undef java_lang_Long_MIN_VALUE
#define java_lang_Long_MIN_VALUE -9223372036854775808LL
#undef java_lang_Long_MAX_VALUE
#define java_lang_Long_MAX_VALUE 9223372036854775807LL
  jlong value;
} Hjava_lang_Long;


#ifdef __cplusplus
}
#endif

#endif
