/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Math
#define _Included_java_lang_Math

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Math */

typedef struct Hjava_lang_Math {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Math: */
#undef java_lang_Math_E
#define java_lang_Math_E 2.7182818284590451E+00
#undef java_lang_Math_PI
#define java_lang_Math_PI 3.1415926535897931E+00
} Hjava_lang_Math;

extern jdouble java_lang_Math_sin(jdouble);
extern jdouble java_lang_Math_cos(jdouble);
extern jdouble java_lang_Math_tan(jdouble);
extern jdouble java_lang_Math_asin(jdouble);
extern jdouble java_lang_Math_acos(jdouble);
extern jdouble java_lang_Math_atan(jdouble);
extern jdouble java_lang_Math_atan2(jdouble, jdouble);
extern jdouble java_lang_Math_exp(jdouble);
extern jdouble java_lang_Math_log(jdouble);
extern jdouble java_lang_Math_sqrt(jdouble);
extern jdouble java_lang_Math_pow(jdouble, jdouble);
extern jdouble java_lang_Math_IEEEremainder(jdouble, jdouble);
extern jdouble java_lang_Math_ceil(jdouble);
extern jdouble java_lang_Math_floor(jdouble);
extern jdouble java_lang_Math_rint(jdouble);

#ifdef __cplusplus
}
#endif

#endif
