/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Short
#define _Included_java_lang_Short

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Short */

typedef struct Hjava_lang_Short {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Number: */
#undef java_lang_Short_serialVersionUID
#define java_lang_Short_serialVersionUID -8742448824652078965LL

  /* Fields from java/lang/Short: */
#undef java_lang_Short_serialVersionUID
#define java_lang_Short_serialVersionUID 7515723908773894738LL
#undef java_lang_Short_MIN_VALUE
#define java_lang_Short_MIN_VALUE -32768L
#undef java_lang_Short_MAX_VALUE
#define java_lang_Short_MAX_VALUE 32767L
  jshort value;
} Hjava_lang_Short;


#ifdef __cplusplus
}
#endif

#endif
