/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Boolean
#define _Included_java_lang_Boolean

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Boolean */

typedef struct Hjava_lang_Boolean {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Boolean: */
#undef java_lang_Boolean_serialVersionUID
#define java_lang_Boolean_serialVersionUID -3665804199014368530LL
  jboolean value;
} Hjava_lang_Boolean;


#ifdef __cplusplus
}
#endif

#endif
