/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_ClassLoader
#define _Included_java_lang_ClassLoader

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_ClassLoader */

typedef struct Hjava_lang_ClassLoader {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/ClassLoader: */
  struct Hjava_util_HashMap* loadedClasses;
  struct Hjava_util_HashMap* definedPackages;
  struct Hjava_lang_ClassLoader* parent;
  jboolean initialized;
  jboolean defaultAssertionStatus;
  struct Hjava_util_Map* packageAssertionStatus;
  struct Hjava_util_Map* classAssertionStatus;
  struct Hjava_lang_Object* vmdata;
} Hjava_lang_ClassLoader;


#ifdef __cplusplus
}
#endif

#endif
