/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_VMTimeZone
#define _Included_java_util_VMTimeZone

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_VMTimeZone */

typedef struct Hjava_util_VMTimeZone {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/VMTimeZone: */
} Hjava_util_VMTimeZone;

extern struct Hjava_lang_String* java_util_VMTimeZone_getSystemTimeZoneId(void);

#ifdef __cplusplus
}
#endif

#endif
