/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_io_VMObjectStreamClass
#define _Included_java_io_VMObjectStreamClass

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_java_io_VMObjectStreamClass_hasClassInitializer(JNIEnv*, jclass, jclass);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setDoubleNative(JNIEnv*, jclass, jobject, jobject, jdouble);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setFloatNative(JNIEnv*, jclass, jobject, jobject, jfloat);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setLongNative(JNIEnv*, jclass, jobject, jobject, jlong);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setIntNative(JNIEnv*, jclass, jobject, jobject, jint);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setShortNative(JNIEnv*, jclass, jobject, jobject, jshort);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setCharNative(JNIEnv*, jclass, jobject, jobject, jchar);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setByteNative(JNIEnv*, jclass, jobject, jobject, jbyte);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setBooleanNative(JNIEnv*, jclass, jobject, jobject, jboolean);
JNIEXPORT void JNICALL Java_java_io_VMObjectStreamClass_setObjectNative(JNIEnv*, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif
