/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_SocketImpl
#define _Included_java_net_SocketImpl

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_SocketImpl */

typedef struct Hjava_net_SocketImpl {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/SocketImpl: */
  struct Hjava_net_InetAddress* address;
  struct Hjava_io_FileDescriptor* fd;
  jint localport;
  jint port;
} Hjava_net_SocketImpl;


#ifdef __cplusplus
}
#endif

#endif
