/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Byte
#define _Included_java_lang_Byte

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Byte */

typedef struct Hjava_lang_Byte {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Number: */
#undef java_lang_Byte_serialVersionUID
#define java_lang_Byte_serialVersionUID -8742448824652078965LL

  /* Fields from java/lang/Byte: */
#undef java_lang_Byte_serialVersionUID
#define java_lang_Byte_serialVersionUID -7183698231559129828LL
#undef java_lang_Byte_MIN_VALUE
#define java_lang_Byte_MIN_VALUE -128L
#undef java_lang_Byte_MAX_VALUE
#define java_lang_Byte_MAX_VALUE 127L
  jbyte value;
} Hjava_lang_Byte;


#ifdef __cplusplus
}
#endif

#endif
