/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_zip_Deflater
#define _Included_java_util_zip_Deflater

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_zip_Deflater */

typedef struct Hjava_util_zip_Deflater {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/zip/Deflater: */
#undef java_util_zip_Deflater_DEFLATED
#define java_util_zip_Deflater_DEFLATED 8L
#undef java_util_zip_Deflater_NO_COMPRESSION
#define java_util_zip_Deflater_NO_COMPRESSION 0L
#undef java_util_zip_Deflater_BEST_SPEED
#define java_util_zip_Deflater_BEST_SPEED 1L
#undef java_util_zip_Deflater_BEST_COMPRESSION
#define java_util_zip_Deflater_BEST_COMPRESSION 9L
#undef java_util_zip_Deflater_DEFAULT_COMPRESSION
#define java_util_zip_Deflater_DEFAULT_COMPRESSION -1L
#undef java_util_zip_Deflater_FILTERED
#define java_util_zip_Deflater_FILTERED 1L
#undef java_util_zip_Deflater_HUFFMAN_ONLY
#define java_util_zip_Deflater_HUFFMAN_ONLY 2L
#undef java_util_zip_Deflater_DEFAULT_STRATEGY
#define java_util_zip_Deflater_DEFAULT_STRATEGY 0L
  jint strm;
  HArrayOfByte* buf;
  jint off;
  jint len;
  jint level;
  jint strategy;
  jboolean finish;
  jboolean finished;
} Hjava_util_zip_Deflater;

extern void java_util_zip_Deflater_setDictionary(struct Hjava_util_zip_Deflater*, HArrayOfByte*, jint, jint);
extern jint java_util_zip_Deflater_deflate(struct Hjava_util_zip_Deflater*, HArrayOfByte*, jint, jint);
extern jint java_util_zip_Deflater_getAdler(struct Hjava_util_zip_Deflater*);
extern jint java_util_zip_Deflater_getTotalIn(struct Hjava_util_zip_Deflater*);
extern jint java_util_zip_Deflater_getTotalOut(struct Hjava_util_zip_Deflater*);
extern void java_util_zip_Deflater_reset(struct Hjava_util_zip_Deflater*);
extern void java_util_zip_Deflater_end(struct Hjava_util_zip_Deflater*);
extern void java_util_zip_Deflater_init(struct Hjava_util_zip_Deflater*, jboolean);

#ifdef __cplusplus
}
#endif

#endif
