/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_lang_VMProcess
#define _Included_java_lang_VMProcess

#ifdef __cplusplus
extern "C" {
#endif

#undef java_lang_VMProcess_INITIAL
#define java_lang_VMProcess_INITIAL 0L
#undef java_lang_VMProcess_RUNNING
#define java_lang_VMProcess_RUNNING 1L
#undef java_lang_VMProcess_TERMINATED
#define java_lang_VMProcess_TERMINATED 2L
JNIEXPORT void JNICALL Java_java_lang_VMProcess_nativeSpawn(JNIEnv*, jobject, jobjectArray, jobjectArray, jobject);
JNIEXPORT jboolean JNICALL Java_java_lang_VMProcess_nativeReap(JNIEnv*, jclass);
JNIEXPORT void JNICALL Java_java_lang_VMProcess_nativeKill(JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif
