/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_VMNetworkInterface
#define _Included_java_net_VMNetworkInterface

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_VMNetworkInterface */

typedef struct Hjava_net_VMNetworkInterface {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/VMNetworkInterface: */
} Hjava_net_VMNetworkInterface;

extern struct Hjava_util_Vector* java_net_VMNetworkInterface_getInterfaces(void);

#ifdef __cplusplus
}
#endif

#endif
