/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_DatagramPacket
#define _Included_java_net_DatagramPacket

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_DatagramPacket */

typedef struct Hjava_net_DatagramPacket {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/DatagramPacket: */
  HArrayOfByte* buffer;
  jint offset;
  jint length;
  jint maxlen;
  struct Hjava_net_InetAddress* address;
  jint port;
} Hjava_net_DatagramPacket;


#ifdef __cplusplus
}
#endif

#endif
