/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_Thread
#define _Included_java_lang_Thread

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_Thread */

typedef struct Hjava_lang_Thread {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/Thread: */
#undef java_lang_Thread_MIN_PRIORITY
#define java_lang_Thread_MIN_PRIORITY 1L
#undef java_lang_Thread_NORM_PRIORITY
#define java_lang_Thread_NORM_PRIORITY 5L
#undef java_lang_Thread_MAX_PRIORITY
#define java_lang_Thread_MAX_PRIORITY 10L
  struct Hjava_lang_VMThread* vmThread;
  struct Hjava_lang_ThreadGroup* group;
  struct Hjava_lang_Runnable* runnable;
  struct Hjava_lang_String* name;
  jboolean daemon;
  jint priority;
  jlong stacksize;
  struct Hjava_lang_Throwable* stillborn;
  struct Hjava_lang_ClassLoader* contextClassLoader;
  struct Hjava_util_WeakHashMap* locals;
} Hjava_lang_Thread;


#ifdef __cplusplus
}
#endif

#endif
