/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_reflect_Field
#define _Included_java_lang_reflect_Field

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_reflect_Field */

typedef struct Hjava_lang_reflect_Field {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/reflect/AccessibleObject: */
  jboolean flag;

  /* Fields from java/lang/reflect/Field: */
  struct Hjava_lang_Class* clazz;
  jint slot;
  struct Hjava_lang_String* name;
  struct Hjava_lang_Class* type;
} Hjava_lang_reflect_Field;

extern jint java_lang_reflect_Field_getModifiers(struct Hjava_lang_reflect_Field*);
extern jboolean java_lang_reflect_Field_getBoolean0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jbyte java_lang_reflect_Field_getByte0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jchar java_lang_reflect_Field_getChar0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jshort java_lang_reflect_Field_getShort0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jint java_lang_reflect_Field_getInt0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jlong java_lang_reflect_Field_getLong0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jfloat java_lang_reflect_Field_getFloat0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern jdouble java_lang_reflect_Field_getDouble0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern struct Hjava_lang_Object* java_lang_reflect_Field_getObject0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*);
extern void java_lang_reflect_Field_setBoolean0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jboolean);
extern void java_lang_reflect_Field_setByte0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jbyte);
extern void java_lang_reflect_Field_setChar0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jchar);
extern void java_lang_reflect_Field_setShort0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jshort);
extern void java_lang_reflect_Field_setInt0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jint);
extern void java_lang_reflect_Field_setLong0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jlong);
extern void java_lang_reflect_Field_setFloat0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jfloat);
extern void java_lang_reflect_Field_setDouble0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, jdouble);
extern void java_lang_reflect_Field_setObject0(struct Hjava_lang_reflect_Field*, struct Hjava_lang_Object*, struct Hjava_lang_Object*);

#ifdef __cplusplus
}
#endif

#endif
