/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_io_VMFile
#define _Included_java_io_VMFile

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_io_VMFile */

typedef struct Hjava_io_VMFile {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/io/VMFile: */
#undef java_io_VMFile_IS_CASE_SENSITIVE
#define java_io_VMFile_IS_CASE_SENSITIVE 1L
#undef java_io_VMFile_IS_DOS_8_3
#define java_io_VMFile_IS_DOS_8_3 0L
} Hjava_io_VMFile;

extern jlong java_io_VMFile_lastModified(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_setReadOnly(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_create(struct Hjava_lang_String*);
extern HArrayOfObject* java_io_VMFile_list(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_renameTo(struct Hjava_lang_String*, struct Hjava_lang_String*);
extern jlong java_io_VMFile_length(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_exists(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_delete(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_setLastModified(struct Hjava_lang_String*, jlong);
extern jboolean java_io_VMFile_mkdir(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_isFile(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_canWrite(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_canRead(struct Hjava_lang_String*);
extern jboolean java_io_VMFile_isDirectory(struct Hjava_lang_String*);

#ifdef __cplusplus
}
#endif

#endif
