/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_net_VMInetAddress
#define _Included_java_net_VMInetAddress

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_net_VMInetAddress */

typedef struct Hjava_net_VMInetAddress {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/net/VMInetAddress: */
} Hjava_net_VMInetAddress;

extern struct Hjava_lang_String* java_net_VMInetAddress_getLocalHostname(void);
extern HArrayOfByte* java_net_VMInetAddress_lookupInaddrAny(void);

#ifdef __cplusplus
}
#endif

#endif
