/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_zip_Inflater
#define _Included_java_util_zip_Inflater

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_zip_Inflater */

typedef struct Hjava_util_zip_Inflater {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/zip/Inflater: */
  jint strm;
  HArrayOfByte* buf;
  jint off;
  jint len;
  jboolean finished;
  jboolean needsDictionary;
} Hjava_util_zip_Inflater;

extern void java_util_zip_Inflater_setDictionary(struct Hjava_util_zip_Inflater*, HArrayOfByte*, jint, jint);
extern jint java_util_zip_Inflater_inflate0(struct Hjava_util_zip_Inflater*, HArrayOfByte*, jint, jint);
extern jint java_util_zip_Inflater_getAdler(struct Hjava_util_zip_Inflater*);
extern jint java_util_zip_Inflater_getTotalIn(struct Hjava_util_zip_Inflater*);
extern jint java_util_zip_Inflater_getTotalOut(struct Hjava_util_zip_Inflater*);
extern void java_util_zip_Inflater_reset(struct Hjava_util_zip_Inflater*);
extern void java_util_zip_Inflater_init(struct Hjava_util_zip_Inflater*, jboolean);
extern void java_util_zip_Inflater_end(struct Hjava_util_zip_Inflater*);

#ifdef __cplusplus
}
#endif

#endif
