/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_util_zip_ZipFile
#define _Included_java_util_zip_ZipFile

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_util_zip_ZipFile */

typedef struct Hjava_util_zip_ZipFile {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/util/zip/ZipFile: */
#undef java_util_zip_ZipFile_OPEN_READ
#define java_util_zip_ZipFile_OPEN_READ 1L
#undef java_util_zip_ZipFile_OPEN_DELETE
#define java_util_zip_ZipFile_OPEN_DELETE 4L
  struct Hjava_lang_String* name;
  struct Hkaffe_util_Ptr* zip;
  jboolean closed;
} Hjava_util_zip_ZipFile;

extern struct Hkaffe_util_Ptr* java_util_zip_ZipFile_openZipFile0(struct Hjava_lang_String*);
extern void java_util_zip_ZipFile_closeZipFile0(struct Hkaffe_util_Ptr*);
extern struct Hjava_util_zip_ZipEntry* java_util_zip_ZipFile_getZipEntry0(struct Hkaffe_util_Ptr*, struct Hjava_lang_String*);
extern struct Hjava_util_Vector* java_util_zip_ZipFile_getZipEntries0(struct Hkaffe_util_Ptr*);
extern HArrayOfByte* java_util_zip_ZipFile_getZipData0(struct Hkaffe_util_Ptr*, struct Hjava_util_zip_ZipEntry*);
extern jint java_util_zip_ZipFile_getZipFileSize0(struct Hkaffe_util_Ptr*);

#ifdef __cplusplus
}
#endif

#endif
