/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_java_lang_StackTraceElement
#define _Included_java_lang_StackTraceElement

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class java_lang_StackTraceElement */

typedef struct Hjava_lang_StackTraceElement {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from java/lang/StackTraceElement: */
#undef java_lang_StackTraceElement_serialVersionUID
#define java_lang_StackTraceElement_serialVersionUID 6992337162326171013LL
  struct Hjava_lang_String* fileName;
  jint lineNumber;
  struct Hjava_lang_String* declaringClass;
  struct Hjava_lang_String* methodName;
  jboolean isNative;
} Hjava_lang_StackTraceElement;


#ifdef __cplusplus
}
#endif

#endif
