/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_java_lang_VMSystem
#define _Included_java_lang_VMSystem

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_java_lang_VMSystem_arraycopy0(JNIEnv*, jclass, jobject, jint, jobject, jint, jint);
JNIEXPORT jint JNICALL Java_java_lang_VMSystem_identityHashCode(JNIEnv*, jclass, jobject);
JNIEXPORT void JNICALL Java_java_lang_VMSystem_setIn(JNIEnv*, jclass, jobject);
JNIEXPORT void JNICALL Java_java_lang_VMSystem_setOut(JNIEnv*, jclass, jobject);
JNIEXPORT void JNICALL Java_java_lang_VMSystem_setErr(JNIEnv*, jclass, jobject);
JNIEXPORT jlong JNICALL Java_java_lang_VMSystem_currentTimeMillis(JNIEnv*, jclass);
JNIEXPORT jstring JNICALL Java_java_lang_VMSystem_getenv(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif
