/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_kaffe_management_Classpath
#define _Included_kaffe_management_Classpath

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class kaffe_management_Classpath */

typedef struct Hkaffe_management_Classpath {
  /* Fields from java/lang/Object: */
  Hjava_lang_Object base;

  /* Fields from kaffe/management/Classpath: */
} Hkaffe_management_Classpath;

extern void kaffe_management_Classpath_add0(struct Hjava_lang_String*);
extern void kaffe_management_Classpath_prepend0(struct Hjava_lang_String*);

#ifdef __cplusplus
}
#endif

#endif
