/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_kaffe_management_Debug
#define _Included_kaffe_management_Debug

#ifdef __cplusplus
extern "C" {
#endif

#undef kaffe_management_Debug_GC_QUIET
#define kaffe_management_Debug_GC_QUIET 0L
#undef kaffe_management_Debug_GC_REPORT
#define kaffe_management_Debug_GC_REPORT 1L
#undef kaffe_management_Debug_GC_STATISTICS
#define kaffe_management_Debug_GC_STATISTICS 2L
JNIEXPORT void JNICALL Java_kaffe_management_Debug_enable(JNIEnv*, jclass, jstring);
JNIEXPORT void JNICALL Java_kaffe_management_Debug_setVerboseGC(JNIEnv*, jclass, jint);
JNIEXPORT void JNICALL Java_kaffe_management_Debug_setVerboseJIT(JNIEnv*, jclass, jboolean);
JNIEXPORT void JNICALL Java_kaffe_management_Debug_enableStats(JNIEnv*, jclass, jstring);
JNIEXPORT void JNICALL Java_kaffe_management_Debug_setTracing(JNIEnv*, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif
