/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_kaffe_management_XProfiler
#define _Included_kaffe_management_XProfiler

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_kaffe_management_XProfiler_on(JNIEnv*, jclass);
JNIEXPORT void JNICALL Java_kaffe_management_XProfiler_off(JNIEnv*, jclass);
JNIEXPORT void JNICALL Java_kaffe_management_XProfiler_stage(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif
