/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_kaffe_lang_UNIXProcess
#define _Included_kaffe_lang_UNIXProcess

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_kaffe_lang_UNIXProcess_forkAndExec(JNIEnv*, jobject, jobjectArray, jobjectArray, jstring);
JNIEXPORT jint JNICALL Java_kaffe_lang_UNIXProcess_execWait(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_kaffe_lang_UNIXProcess_sendSignal0(JNIEnv*, jclass, jint, jint);
JNIEXPORT jint JNICALL Java_kaffe_lang_UNIXProcess_getKillSignal(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif

#endif
