/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_kaffe_security_provider_MD2
#define _Included_kaffe_security_provider_MD2

#ifdef __cplusplus
extern "C" {
#endif

#undef kaffe_security_provider_MD2_MESSAGE_DIGEST
#define kaffe_security_provider_MD2_MESSAGE_DIGEST "MessageDigest"
#undef kaffe_security_provider_MD2_DIGEST_NAME
#define kaffe_security_provider_MD2_DIGEST_NAME "MD2"
#undef kaffe_security_provider_MD2_DIGEST_LENGTH
#define kaffe_security_provider_MD2_DIGEST_LENGTH 16L
JNIEXPORT void JNICALL Java_kaffe_security_provider_MD2_Init(JNIEnv*, jobject);
JNIEXPORT void JNICALL Java_kaffe_security_provider_MD2_Update(JNIEnv*, jobject, jbyteArray, jint, jint);
JNIEXPORT void JNICALL Java_kaffe_security_provider_MD2_Final(JNIEnv*, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif

#endif
