/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_kaffe_management_JIT
#define _Included_kaffe_management_JIT

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_kaffe_management_JIT_translateMethod(JNIEnv*, jclass, jstring, jstring, jstring, jobject);
JNIEXPORT void JNICALL Java_kaffe_management_JIT_flushCache(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif

#endif
