RGSRC=../../../../..
include $(RGSRC)/envir.mak
include $(RGSRC)/pkg/voip/asterisk/db1-ast/common.mak

O_TARGET=hash_target.o
O_OBJS=hash.o hash_bigkey.o hash_buf.o hash_func.o hash_log2.o hash_page.o \
  hsearch.o ndbm.o

include $(RGMK)
