RGSRC=../../../../..
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../../../envir.mak

SO_TARGET=libsecurity.so
O_OBJS=digest.o kaffe_md5.o sha-1.o

RAMDISK_LIB_FILES+=libsecurity.so

include $(RGMK)
