linux=1
LINUX=1
HAVE_GETPID=1
HAVE_EXECV=1
HAVE_SYSTEM=1
HAVE_SYSLOG_H=1
HAVE_MKSTEMP=1
HAVE_SYS_UTSNAME_H=1
HAVE_SYS_UN_H=1
HAVE_ALARM=1
HAVE_PWD_H=1
HAVE_GRP_H=1
HAVE_GETUID=1
HAVE_SETENV=1
HAVE___PROGNAME=1
HAVE_KILL=1
HAVE_KILLPG=1
HAVE_PROC_UPTIME=1
HAVE_SETENV=1
HAVE_SYSLOG_H=1

#Define if you have the setenv function.
HAVE_SETENV=1

#Define if you have the <grp.h> header file.
HAVE_GRP_H=1
