RGSRC=../../../..
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../../envir.mak

# Order is important, due to library dependencies.
SUBDIRS=classpath fdlibm nio io management math native net security zip 

include $(RGMK)
