RGSRC=../../../../
include $(RGSRC)/envir.mak
include $(PWD_SRC)/../crypto_env.mak

EXPORT_HEADERS=rand.h
INTERNAL_HEADERS=rand_lcl.h

O_OBJS=md_rand.o randfile.o rand_lib.o rand_err.o rand_egd.o rand_unix.o

include $(RGMK)

