# File: drivers/at91/i2c/Makefile
#
# Makefile for the Atmel AT91RM9200 I2C (TWI) device drivers
#

O_TARGET := at91i2c.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_I2C_AT91) += at91_i2c.o

include $(TOPDIR)/Rules.make
