RGSRC=../../../
include $(RGSRC)/envir.mak

EXPORT_HEADERS_DIR+=ebtree
SUBDIRS+=
EXPORT_HEADERS+=compiler.h  eb32tree.h  eb64tree.h  ebimtree.h  ebistree.h  ebmbtree.h  ebpttree.h  ebsttree.h  ebtree.h

include $(RGMK)





