# File: drivers/at91/rtc/Makefile
#
# Makefile for the Atmel AT91RM9200 real time clock device drivers
#

O_TARGET := at91rtc.o

obj-y	:=
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_AT91_RTC) += at91_rtc.o

include $(TOPDIR)/Rules.make
