# File: drivers/at91/net/Makefile
#
# Makefile for the Atmel AT91RM9200 ethernet device drivers
#

O_TARGET := at91net.o

obj-y   :=
obj-m   :=
obj-n   :=
obj-	:=

obj-$(CONFIG_AT91_ETHER) += at91_ether.o

include $(TOPDIR)/Rules.make
